name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.1
    - name: Copy secret data
      run: copy SecretData1.cs SecretData.cs
    - name: Setup NuGet.exe for use with action
      uses: NuGet/setup-nuget@v1.0.6
    - name: restore
      run: nuget restore
    - name: Restore dependencies
      run: msbuild ClipAngel.sln /property:Configuration=Release
    - uses: actions/upload-artifact@v3
      with:
        name: binaries
        path: bin/release
